### ISSUE TITLE
help for documenting freeList

### ISSUE THREAD

**Issue by hogoww** [SquareBracketAssociates/Booklet-PharoVirtualMachine#5]
This test was working in 64 but not in 32. we were missing a bit of documentation.
This is a basis for future writting on the freelist topic.

testAllocatePowerInListShouldIgnoreNonPowers

	| sizeToAllocate powerOfSizeToAllocate nonMultipleAddress newAddress |
	"bitSize * allocationUnit equals maxChunckSize in the freeList
	The freeList has bitsPerWords slots.
	Each slots contains a pointer (wordsize), which behaves as a linked list.
	Each linked list contains links free chunks of the same size.
	The nodeSize of each list equals index * allocationUnit.
	For example in 32 bits the free list will have 31 slots (1 for reserved for the tree).
	The last linked list is stored at index 31 (0 based) and will contain nodes of size 248 (index * 8)."
	sizeToAllocate := 10 * wordSize.
	powerOfSizeToAllocate := sizeToAllocate * (2 ** 2).
	
	nonMultipleAddress := self createFreeChunkOfSize: 120.
	
	self createFreeChunkOfSize: powerOfSizeToAllocate.
	
	newAddress := memory allocateOldSpaceChunkOfBytes: sizeToAllocate.
	self deny: newAddress equals: nonMultipleAddress.

**Comment by guillep** [comment]
We will take care of it, thanks
